### ISSUE TITLE
remove redundant build default script

### ISSUE THREAD

**Issue by yinonov** [afc163/surge-preview#231]
one of the action parameters is `build`, which has a default script.
if not provided by the consuming action, it will run a redundant script `npm install` etc'.

I had to just set some random command to override it. maybe it's redundant?

```yml
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Site
        run: npm run nx build docs

      - name: Deploy
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: dist/apps/docs
          teardown: 'true'
          build: echo # required to override default script that may damage the setup

      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"

```
