### ISSUE TITLE
Feature request: Add option to auto teardown a preview after merge/close

### ISSUE THREAD

**Issue by lwhiteley** [afc163/surge-preview#35]
Add an option that will teardown a preview preview when a pull request is closed

This can be configurable, maybe: `teardown: "true" or "false"`?
When the event action is `closed` then run the `surge teardown <pr-preview-url>`

it makes sense for this action to take care of it to ensure the url is generated by one utility

```yaml
name: teardown

on:
  pull_request:
    types: [closed]

jobs:
  teardown-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@{version}
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          teardown: 'true'
```
