### ISSUE TITLE
html 单文件预览 如何预览？

### ISSUE THREAD

**Issue by xrkffgg** [afc163/surge-preview#61]
比如 项目中只有一个 index.html 在根目录，引入一些 css，没有 build 命令，dist 也是根目录

**Comment by afc163** [comment]
```
name: 🔂 Surge PR Preview

on: pull_request_target

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: ./
```

试试。

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/98674972-93660200-2394-11eb-9adf-8b5b733fcb00.png)

我看代码，如果没有 build ，会默认 install 和 build ，现在没有 package.json ，走 install 就报错了

**Comment by afc163** [comment]
```
name: 🔂 Surge PR Preview

on: pull_request_target

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: echo 'nothing'
          dist: ./
```
